services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: npm run start:dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    command: postgres -c 'log_statement=all'
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: